Upgrade ES DSL lib to fix missing shards error.
Got this error:

Traceback (most recent call last):
File "loader.py", line 23, in <module>
load_recent_pricefeeds()
File "/usr/src/app/bitshares_pricefeed_tracker/loader.py", line 83, in load_recent_pricefeeds
count = load_pricefeeds(start.isoformat(), end_string)
File "/usr/src/app/bitshares_pricefeed_tracker/loader.py", line 51, in load_pricefeeds
for hit in s.scan():
File "/usr/local/lib/python3.8/site-packages/elasticsearch_dsl/search.py", line 723, in scan
for hit in scan(
File "/usr/local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 461, in scan
raise ScanError(
elasticsearch.helpers.errors.ScanError: Scroll request has only succeeded on 180 shards out of 270.

Related to this bug fix:
https://github.com/elastic/elasticsearch-py/commit/fc78c992ef6ceca157f369186760c8c550fb3bc4

CF: https://discuss.elastic.co/t/elasticsearch-dsl-python-scanerror/201980